let debts=JSON.parse(localStorage.getItem('debts')||'[]');let currentFilter='all';let currentSort='date-desc';let currentRange=6;let selectedPriority='low';let searchQuery='';let pendingAction=null;let chart=null;window.addEventListener('DOMContentLoaded',()=>{const bar=document.getElementById('loader-bar');const logo=document.querySelector('.loader-logo');const loaderText=document.querySelector('.loader-text');gsap.to(logo,{opacity:1,y:0,duration:0.6,ease:'power2.out',delay:0.2});gsap.to(bar,{width:'100%',duration:1.4,ease:'power2.inOut',delay:0.3});const texts=['Initialising','Loading data','Building UI','Ready'];texts.forEach((t,i)=>{gsap.delayedCall(0.3+i*0.3,()=>{loaderText.textContent=t;});});gsap.delayedCall(1.8,()=>{gsap.to('#loader',{opacity:0,duration:0.5,ease:'power2.in',onComplete:()=>{document.getElementById('loader').style.display='none';initApp();}});});});function initApp(){updateDate();setInterval(updateDate,1000);gsap.to('#header',{opacity:1,duration:0.6,ease:'power2.out'});gsap.from('#header .header-left > *',{opacity:0,y:30,duration:0.7,stagger:0.12,ease:'power3.out',delay:0.1});gsap.from('.header-glow',{scale:0.3,opacity:0,duration:1.2,ease:'power3.out',delay:0.2});gsap.to('#main-content',{opacity:1,duration:0.5,delay:0.3});gsap.to('.stat-card',{opacity:1,y:0,duration:0.6,stagger:0.1,ease:'back.out(1.4)',delay:0.4});gsap.to('.fade-up:not(.stat-card)',{opacity:1,y:0,duration:0.6,stagger:0.08,ease:'power2.out',delay:0.6});renderDebts();renderStats();renderSidebar();renderAverages();initChart();bindEvents();}
function updateDate(){const now=new Date();const d=document.getElementById('header-date');d.innerHTML=`<div><span class="live-dot"></span>Live</div>
      <div>${now.toLocaleDateString('en-GB', { weekday: 'short', day: 'numeric', month: 'short', year: 'numeric' })}</div>
      <div>${now.toLocaleTimeString('en-GB', { hour: '2-digit', minute: '2-digit', second: '2-digit' })}</div>`;}
function renderStats(){const total=debts.length;const paid=debts.filter(d=>d.paid).length;const outstanding=debts.filter(d=>!d.paid).reduce((s,d)=>s+parseFloat(d.amount),0);const paidAmount=debts.filter(d=>d.paid).reduce((s,d)=>s+parseFloat(d.amount),0);animateNumber('stat-total',total,'');animateNumber('stat-paid',paid,'');animateNumber('stat-amount',outstanding,'£');document.getElementById('stat-total-sub').textContent=total===0?'No debts recorded':`${paid} of ${total} cleared`;document.getElementById('stat-paid-sub').textContent=paid>0?`£${paidAmount.toFixed(2)} total`:'—';document.getElementById('stat-amount-sub').textContent=outstanding===0&&total>0?'All clear! 🎉':outstanding>0?`${total - paid} unpaid debts`:'All clear';}
function animateNumber(id,target,prefix){const el=document.getElementById(id);const current=parseFloat(el.textContent.replace(/[^0-9.]/g,''))||0;gsap.to({val:current},{val:target,duration:0.8,ease:'power2.out',onUpdate:function(){if(prefix==='£'){el.textContent=prefix+this.targets()[0].val.toFixed(2);}else{el.textContent=Math.round(this.targets()[0].val);}}});}
function getFilteredDebts(){let list=[...debts];if(currentFilter==='paid')list=list.filter(d=>d.paid);else if(currentFilter==='unpaid')list=list.filter(d=>!d.paid);if(searchQuery){const q=searchQuery.toLowerCase();list=list.filter(d=>d.name.toLowerCase().includes(q)||(d.description||'').toLowerCase().includes(q));}
list.sort((a,b)=>{if(currentSort==='date-desc')return new Date(b.date)-new Date(a.date);if(currentSort==='date-asc')return new Date(a.date)-new Date(b.date);if(currentSort==='amount-desc')return parseFloat(b.amount)-parseFloat(a.amount);if(currentSort==='amount-asc')return parseFloat(a.amount)-parseFloat(b.amount);if(currentSort==='name')return a.name.localeCompare(b.name);return 0;});return list;}
function renderDebts(){const container=document.getElementById('debts-container');const list=getFilteredDebts();if(list.length===0){container.innerHTML=`<div class="empty-state">
        <div class="empty-state-icon">£</div>
        <p>${searchQuery ? 'No matching debts' : 'No debts here'}</p>
      </div>`;return;}
const html=list.map(debt=>{const date=new Date(debt.date).toLocaleDateString('en-GB',{day:'numeric',month:'short',year:'numeric'});const paidDateStr=debt.paidDate?new Date(debt.paidDate).toLocaleDateString('en-GB',{day:'numeric',month:'short'}):'';const p=debt.priority||'none';return`<div class="debt-card ${debt.paid ? 'paid' : ''} priority-${p}" data-id="${debt.id}">
        <div class="debt-priority-indicator ${p}"></div>
        <div class="debt-main">
          <div class="debt-name">${escHtml(debt.name)}</div>
          <div class="debt-meta">
            <span class="status-badge ${debt.paid ? 'badge-paid' : 'badge-unpaid'}">${debt.paid ? '✓ PAID' : '● OWED'}</span>
            <span>${date}</span>
            ${paidDateStr ? `<span>Cleared ${paidDateStr}</span>` : ''}
          </div>
          ${debt.description ? `<div class="debt-desc">${escHtml(debt.description)}</div>` : ''}
        </div>
        <div class="debt-amount ${debt.paid ? 'paid-amount' : ''}">£${parseFloat(debt.amount).toFixed(2)}</div>
        <div class="debt-actions">
          <button class="btn-action btn-paid-toggle ${debt.paid ? 'is-paid' : ''}" onclick="confirmTogglePaid(${debt.id})">${debt.paid ? 'Unmark' : 'Mark Paid'}</button>
          <button class="btn-action btn-delete" onclick="confirmDelete(${debt.id})">Delete</button>
        </div>
      </div>`;}).join('');container.innerHTML=html;gsap.from(container.querySelectorAll('.debt-card'),{opacity:0,x:-20,duration:0.4,stagger:0.05,ease:'power2.out'});}
function renderSidebar(){const topEl=document.getElementById('top-debtors');const unpaid=debts.filter(d=>!d.paid).sort((a,b)=>parseFloat(b.amount)-parseFloat(a.amount));const maxAmount=unpaid[0]?parseFloat(unpaid[0].amount):1;if(unpaid.length===0){topEl.innerHTML='<div class="no-data-text">None outstanding</div>';}else{topEl.innerHTML=unpaid.slice(0,5).map(d=>{const pct=(parseFloat(d.amount)/maxAmount*100).toFixed(0);return`<div class="progress-item">
          <div class="progress-label">
            <span class="progress-name">${escHtml(d.name)}</span>
            <span class="progress-amount">£${parseFloat(d.amount).toFixed(2)}</span>
          </div>
          <div class="progress-track"><div class="progress-fill" style="width:${pct}%"></div></div>
        </div>`;}).join('');}
const recentEl=document.getElementById('recent-paid');const recent=debts.filter(d=>d.paid&&d.paidDate).sort((a,b)=>new Date(b.paidDate)-new Date(a.paidDate));if(recent.length===0){recentEl.innerHTML='<div class="no-data-text">Nothing yet</div>';}else{recentEl.innerHTML=recent.slice(0,4).map(d=>{const dt=new Date(d.paidDate).toLocaleDateString('en-GB',{day:'numeric',month:'short'});return`<div class="progress-item">
          <div class="progress-label">
            <span class="progress-name">${escHtml(d.name)}</span>
            <span class="progress-amount">${dt}</span>
          </div>
          <div class="progress-track"><div class="progress-fill paid-fill" style="width:100%"></div></div>
        </div>`;}).join('');}
const prioEl=document.getElementById('priority-breakdown');const counts={high:0,mid:0,low:0,none:0};debts.filter(d=>!d.paid).forEach(d=>{counts[d.priority||'none']++;});const total=Object.values(counts).reduce((a,b)=>a+b,0)||1;const prioCols={high:'var(--red)',mid:'var(--gold)',low:'var(--green)',none:'var(--text-muted)'};const prioLabels={high:'High',mid:'Medium',low:'Low',none:'Unset'};prioEl.innerHTML=Object.entries(counts).filter(([,v])=>v>0).map(([k,v])=>{const pct=(v/total*100).toFixed(0);return`<div class="progress-item">
        <div class="progress-label">
          <span class="progress-name" style="color:${prioCols[k]}">${prioLabels[k]}</span>
          <span class="progress-amount">${v} debt${v > 1 ? 's' : ''}</span>
        </div>
        <div class="progress-track"><div class="progress-fill" style="width:${pct}%;background:${prioCols[k]}"></div></div>
      </div>`;}).join('')||'<div class="no-data-text">No unpaid debts</div>';}
function initChart(){const ctx=document.getElementById('chart').getContext('2d');chart=new Chart(ctx,{type:'bar',data:{labels:[],datasets:[{label:'Paid (£)',data:[],backgroundColor:'rgba(229,38,58,0.25)',borderColor:'rgba(229,38,58,0.8)',borderWidth:2,borderRadius:6,hoverBackgroundColor:'rgba(229,38,58,0.5)'}]},options:{responsive:true,maintainAspectRatio:false,resizeDelay:0,plugins:{legend:{display:false},tooltip:{backgroundColor:'#1a1e2a',borderColor:'rgba(255,255,255,0.1)',borderWidth:1,titleColor:'#f0f2f7',bodyColor:'#9ca3af',titleFont:{family:'DM Mono',size:11},bodyFont:{family:'DM Mono',size:11},callbacks:{label:c=>` £${c.raw.toFixed(2)}`}}},scales:{x:{grid:{color:'rgba(255,255,255,0.04)'},ticks:{color:'#6b7280',font:{family:'DM Mono',size:10}},border:{color:'rgba(255,255,255,0.06)'}},y:{grid:{color:'rgba(255,255,255,0.04)'},ticks:{color:'#6b7280',font:{family:'DM Mono',size:10},callback:v=>'£'+v},border:{color:'rgba(255,255,255,0.06)'}}},animation:{duration:600,easing:'easeInOutCubic'}}});updateChart();}
function updateChart(){const paid=debts.filter(d=>d.paid&&d.paidDate);const now=new Date();const cutoff=currentRange>0?new Date(now.getFullYear(),now.getMonth()-currentRange+1,1):null;const map={};paid.forEach(d=>{const dt=new Date(d.paidDate);if(cutoff&&dt<cutoff)return;const key=dt.toLocaleDateString('en-GB',{month:'short',year:'2-digit'});map[key]=(map[key]||0)+parseFloat(d.amount);});const labels=[],data=[];if(currentRange>0){for(let i=currentRange-1;i>=0;i--){const d=new Date(now.getFullYear(),now.getMonth()-i,1);const k=d.toLocaleDateString('en-GB',{month:'short',year:'2-digit'});labels.push(k);data.push(map[k]||0);}}else{Object.keys(map).forEach(k=>{labels.push(k);data.push(map[k]);});}
chart.data.labels=labels;chart.data.datasets[0].data=data;chart.update();}
function bindEvents(){const toggle=document.getElementById('form-toggle');const body=document.getElementById('form-body');const chevron=document.getElementById('form-chevron');let formOpen=false;toggle.addEventListener('click',()=>{formOpen=!formOpen;toggle.classList.toggle('open',formOpen);chevron.classList.toggle('open',formOpen);if(formOpen){gsap.to(body,{maxHeight:600,duration:0.5,ease:'power3.out'});gsap.from(body.querySelectorAll('.form-group, .btn-primary'),{opacity:0,y:10,duration:0.3,stagger:0.06,ease:'power2.out',delay:0.1});}else{gsap.to(body,{maxHeight:0,duration:0.4,ease:'power3.in'});}});document.querySelectorAll('.priority-btn').forEach(btn=>{btn.addEventListener('click',()=>{const p=btn.dataset.p;selectedPriority=p;document.querySelectorAll('.priority-btn').forEach(b=>{b.className='priority-btn';if(b.dataset.p===p)b.classList.add(`active-${p}`);});gsap.from(btn,{scale:0.9,duration:0.3,ease:'back.out(2)'});});});document.getElementById('btn-add').addEventListener('click',addDebt);document.getElementById('search-input').addEventListener('input',e=>{searchQuery=e.target.value.trim();renderDebts();});document.querySelectorAll('.filter-tab').forEach(tab=>{tab.addEventListener('click',()=>{currentFilter=tab.dataset.filter;document.querySelectorAll('.filter-tab').forEach(t=>t.classList.remove('active'));tab.classList.add('active');gsap.from(tab,{scale:0.92,duration:0.2,ease:'back.out(2)'});renderDebts();});});const sortStates=['date-desc','date-asc','amount-desc','amount-asc','name'];const sortLabels=['Date ↓','Date ↑','Amount ↓','Amount ↑','Name'];let sortIdx=0;document.getElementById('sort-btn').addEventListener('click',()=>{sortIdx=(sortIdx+1)%sortStates.length;currentSort=sortStates[sortIdx];document.getElementById('sort-label').textContent=sortLabels[sortIdx];gsap.from('#sort-btn',{rotationZ:10,duration:0.2,ease:'power2.out'});renderDebts();});document.querySelectorAll('.chart-range-tab').forEach(tab=>{tab.addEventListener('click',()=>{currentRange=parseInt(tab.dataset.range);document.querySelectorAll('.chart-range-tab').forEach(t=>t.classList.remove('active'));tab.classList.add('active');updateChart();renderAverages();});});document.getElementById('modal-cancel').addEventListener('click',closeModal);document.getElementById('modal-backdrop').addEventListener('click',e=>{if(e.target===document.getElementById('modal-backdrop'))closeModal();});}
function addDebt(){const name=document.getElementById('input-name').value.trim();const amount=parseFloat(document.getElementById('input-amount').value);const desc=document.getElementById('input-desc').value.trim();if(!name){shakeInput('input-name');showToast('Name is required','error');return;}
if(!amount||amount<=0){shakeInput('input-amount');showToast('Enter a valid amount','error');return;}
const debt={id:Date.now(),name,amount:amount.toFixed(2),description:desc,priority:selectedPriority,paid:false,date:new Date().toISOString(),paidDate:null};debts.unshift(debt);save();renderDebts();renderStats();renderSidebar();renderAverages();updateChart();document.getElementById('input-name').value='';document.getElementById('input-amount').value='';document.getElementById('input-desc').value='';currentFilter='all';document.querySelectorAll('.filter-tab').forEach(t=>t.classList.toggle('active',t.dataset.filter==='all'));showToast(`Debt added for ${name}`,'success');gsap.from('#stat-total',{scale:1.15,duration:0.4,ease:'back.out(2)'});}
function shakeInput(id){const el=document.getElementById(id);gsap.timeline().to(el,{x:-8,duration:0.07,ease:'power2.out'}).to(el,{x:8,duration:0.07}).to(el,{x:-6,duration:0.07}).to(el,{x:6,duration:0.07}).to(el,{x:0,duration:0.07});el.style.borderColor='rgba(229,38,58,0.6)';setTimeout(()=>el.style.borderColor='',1000);}
function confirmTogglePaid(id){const debt=debts.find(d=>d.id===id);if(!debt)return;if(debt.paid){showModal({icon:'↩',iconClass:'warning',title:'Mark as Unpaid?',body:`This will mark <strong>${escHtml(debt.name)}</strong>'s debt of <strong>£${parseFloat(debt.amount).toFixed(2)}</strong> as unpaid again.`,confirmText:'Mark Unpaid',confirmClass:'btn-modal-confirm-red',onConfirm:()=>togglePaid(id)});}else{showModal({icon:'✓',iconClass:'success',title:'Mark as Paid?',body:`Confirm that <strong>${escHtml(debt.name)}</strong>'s debt of <strong>£${parseFloat(debt.amount).toFixed(2)}</strong> has been paid.`,confirmText:'Confirm Paid',confirmClass:'btn-modal-confirm-green',onConfirm:()=>togglePaid(id)});}}
function confirmDelete(id){const debt=debts.find(d=>d.id===id);if(!debt)return;showModal({icon:'⌫',iconClass:'danger',title:'Delete Debt?',body:`This will permanently remove <strong>${escHtml(debt.name)}</strong>'s debt of <strong>£${parseFloat(debt.amount).toFixed(2)}</strong>. This cannot be undone.`,confirmText:'Delete',confirmClass:'btn-modal-confirm-red',onConfirm:()=>deleteDebt(id)});}
function togglePaid(id){const debt=debts.find(d=>d.id===id);if(!debt)return;debt.paid=!debt.paid;debt.paidDate=debt.paid?new Date().toISOString():null;save();renderDebts();renderStats();renderSidebar();renderAverages();updateChart();showToast(debt.paid?`${debt.name} marked as paid`:`${debt.name} marked as unpaid`,debt.paid?'success':'info');}
function deleteDebt(id){const debt=debts.find(d=>d.id===id);const card=document.querySelector(`[data-id="${id}"]`);if(card){gsap.to(card,{opacity:0,x:30,height:0,marginBottom:0,paddingTop:0,paddingBottom:0,duration:0.35,ease:'power2.in',onComplete:()=>{debts=debts.filter(d=>d.id!==id);save();renderDebts();renderStats();renderSidebar();renderAverages();updateChart();}});}else{debts=debts.filter(d=>d.id!==id);save();renderDebts();renderStats();renderSidebar();renderAverages();updateChart();}
if(debt)showToast(`Deleted ${debt.name}`,'error');}
function showModal({icon,iconClass,title,body,confirmText,confirmClass,onConfirm}){document.getElementById('modal-icon').textContent=icon;document.getElementById('modal-icon').className=`modal-icon ${iconClass}`;document.getElementById('modal-title').textContent=title;document.getElementById('modal-body').innerHTML=body;const confirmBtn=document.getElementById('modal-confirm');confirmBtn.textContent=confirmText;confirmBtn.className=`btn-modal ${confirmClass}`;pendingAction=onConfirm;confirmBtn.onclick=()=>{pendingAction&&pendingAction();closeModal();};const backdrop=document.getElementById('modal-backdrop');backdrop.classList.add('open');gsap.from('.modal',{scale:0.88,y:30,opacity:0,duration:0.4,ease:'back.out(1.4)'});}
function closeModal(){const backdrop=document.getElementById('modal-backdrop');gsap.to('.modal',{scale:0.95,y:10,opacity:0,duration:0.25,ease:'power2.in',onComplete:()=>{backdrop.classList.remove('open');gsap.set('.modal',{clearProps:'all'});}});pendingAction=null;}
function showToast(msg,type='info'){const el=document.createElement('div');el.className=`toast toast-${type}`;el.innerHTML=`<div class="toast-dot"></div><span>${msg}</span>`;document.getElementById('toast-container').appendChild(el);gsap.to(el,{x:0,opacity:1,duration:0.4,ease:'back.out(1.4)'});gsap.to(el,{x:120,opacity:0,duration:0.3,ease:'power2.in',delay:2.5,onComplete:()=>el.remove()});}
function exportJSON(){const blob=new Blob([JSON.stringify(debts,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`debt-tracker-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(url);showToast(`Exported ${debts.length} debt${debts.length !== 1 ? 's' : ''} as JSON`,'success');gsap.from('.btn-export-json',{scale:0.88,duration:0.3,ease:'back.out(2)'});}
function exportCSV(){const headers=['ID','Name','Amount','Description','Priority','Paid','Date Added','Paid Date'];const rows=debts.map(d=>[d.id,`"${(d.name || '').replace(/"/g,'""')}"`,d.amount,`"${(d.description || '').replace(/"/g,'""')}"`,d.priority||'none',d.paid?'Yes':'No',d.date?new Date(d.date).toLocaleDateString('en-GB'):'',d.paidDate?new Date(d.paidDate).toLocaleDateString('en-GB'):''].join(','));const csv=[headers.join(','),...rows].join('\n');const blob=new Blob([csv],{type:'text/csv'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`debt-tracker-${new Date().toISOString().slice(0,10)}.csv`;a.click();URL.revokeObjectURL(url);showToast(`Exported ${debts.length} debt${debts.length !== 1 ? 's' : ''} as CSV`,'success');gsap.from('.btn-export-csv',{scale:0.88,duration:0.3,ease:'back.out(2)'});}
function triggerImport(){document.getElementById('import-file').value='';document.getElementById('import-file').click();}
function importJSON(event){const file=event.target.files[0];if(!file)return;const reader=new FileReader();reader.onload=e=>{try{const parsed=JSON.parse(e.target.result);if(!Array.isArray(parsed))throw new Error('Not an array');const valid=parsed.filter(d=>d.id&&d.name&&d.amount!==undefined);if(valid.length===0)throw new Error('No valid debts found');const existing=new Set(debts.map(d=>d.id));const incoming=valid.filter(d=>!existing.has(d.id));const duplicates=valid.length-incoming.length;debts=[...incoming,...debts];save();renderDebts();renderStats();renderSidebar();renderAverages();updateChart();let msg=`Imported ${incoming.length} debt${incoming.length !== 1 ? 's' : ''}`;if(duplicates>0)msg+=` (${duplicates} duplicate${duplicates > 1 ? 's' : ''} skipped)`;showToast(msg,'success');gsap.from('.btn-import',{scale:0.88,duration:0.3,ease:'back.out(2)'});}catch(err){showToast('Import failed: invalid file','error');}};reader.readAsText(file);}
function calcAvgForRange(months){if(debts.length===0)return null;let subset;if(months===0){subset=debts;}else{const now=new Date();const cutoff=new Date(now.getFullYear(),now.getMonth()-months+1,1);subset=debts.filter(d=>new Date(d.date)>=cutoff);}
if(subset.length===0)return null;const total=subset.reduce((s,d)=>s+parseFloat(d.amount),0);return total/subset.length;}
function renderAverages(){const ranges=[{id:'avg-val-all',rowId:'avg-all',months:0,label:'all'},{id:'avg-val-12m',rowId:'avg-12m',months:12,label:'12m'},{id:'avg-val-6m',rowId:'avg-6m',months:6,label:'6m'},];const activeLabel=currentRange===0?'all':currentRange===12?'12m':'6m';ranges.forEach(({id,rowId,months,label})=>{const avg=calcAvgForRange(months);const el=document.getElementById(id);const row=document.getElementById(rowId);const prev=parseFloat(el.dataset.prev||0)||0;const next=avg!==null?avg:0;if(avg===null){el.textContent='£—';}else{gsap.to({v:prev},{v:next,duration:0.7,ease:'power2.out',onUpdate:function(){el.textContent='£'+this.targets()[0].v.toFixed(2);},onComplete:()=>{el.dataset.prev=next;}});}
row.classList.toggle('avg-range-highlight',label===activeLabel);});}
function save(){localStorage.setItem('debts',JSON.stringify(debts));}
function escHtml(s){return s.replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');}